name: Netlify Test Probe

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    if: ${{ secrets.NETLIFY_AUTH_TOKEN != '' }}
    steps:
      - run: echo probe-if-ok
