name: Netlify Test Probe

on:
  push:
    branches: [master]

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: check secret
        env:
          MY_SECRET: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [ -z "$MY_SECRET" ]; then echo "SECRET_IS_EMPTY"; else echo "SECRET_IS_SET"; fi
