name: Netlify Test Probe

on:
  push:
    branches: [master]

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: step if secret
        if: ${{ secrets.NETLIFY_AUTH_TOKEN != '' }}
        run: echo step-if-secret-ok
